### ISSUE TITLE
Search based on 'owner' field works inconsistently between categories

### ISSUE THREAD

**Issue by harriha** [futurice/inventory#19]
There seems to be some inconsistencies on how the search field works in regards of the 'owner' field. In some categories, such as the Devsim category, filtering results based on person needs to be done with username and typing in, for instance, a first name doesn't return any results. This, however, seems to work fine in some categories (e.g., 'Tablet').

*To reproduce:*

- Open Inventory -> Devsim category
- type in a first name of a person who has loaned a Devsim

*Expected:* results are filtered based on that given name

*Actual:* no results

Do the same via giving the username of the person in question -> things work fine.

Repeat the same in 'Tablet' category and compare the behavior.

The problematic categories seem to be 'Devsim' and 'Dongle', others seem to work fine afaics.

**Comment by MihaiFtr** [comment]
Thanks, solved. But please reopen if you notice problems.
