### ISSUE TITLE
Remove ---extra-index-url=http://pypi.fum.futurice.com/simple/ from requirements.txt

### ISSUE THREAD

**Issue by MihaiFtr** [futurice/inventory#4]
Newer django-history==0.2.2 is public.
django-jsonmodel isn't found by `pip install`.

**Comment by mixman** [comment]
Seems I need to package https://github.com/futurice/django-jsonmodel

**Comment by MihaiFtr** [comment]
Yes, and I'll finish the Travis-CI after that.
